# -*- coding: utf-8 -*-
"""Edge-Primer Design for a Given Sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NeZuUjIhDNrh91X_KzfpXmtJ2LcvpTQ
"""

def reverse_complement(sequence: str) -> str:

    # Define complement pairing
    complement_table = str.maketrans("ATGC", "TACG")

    # Convert to uppercase to handle mixed-case inputs
    sequence = sequence.upper()

    # Generate reverse complement
    return sequence[::-1].translate(complement_table)


user_input = "ATGCGGGCGAGCGTTTCGGAGGGTATTTATTATCTTTCTATCATTTTTTAGGGGAGGATTTTAGGGGATTATCTCTCGATCGATTATCGATC"
print(reverse_complement(user_input))