# -*- coding: utf-8 -*-
"""Enzyme Restriction Small Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0UxCTUCX8I179_7kQ-kSgfYSbOOvh45
"""

def restrict_dna(sequence, restriction_site):
    sequence = sequence.upper()
    restriction_site = restriction_site.upper()
    if restriction_site not in sequence:
        print("Restriction site not found in the sequence.")
        return [sequence]

    fragments = sequence.split(restriction_site)

    for i in range(len(fragments) - 1):
        fragments[i] += restriction_site

    return fragments
if __name__ == "__main__":
    dna_sequence = "ATGCGTACGTAGCTACGTAGCTAGCTACGT"
    restriction_site = "ACGT"

    fragments = restrict_dna(dna_sequence, restriction_site)

    print("Original DNA sequence:")
    print(dna_sequence)
    print("\nRestriction site:")
    print(restriction_site)
    print("\nFragments after restriction:")
    for i, fragment in enumerate(fragments, 1):
        print(f"Fragment {i}: {fragment}")