# -*- coding: utf-8 -*-
"""melting temp calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWN-SXger8flICK_U6xsfFaerjB6tc8z
"""

##melting temp calculator with Wallace rule

def reverse_comp(sequence):
    complement = ''
    comp = {
        'T': 'A', 'C': 'G', 'A': 'T', 'G': 'C'
    }
    for nucleotide in sequence:
        complement += comp.get(nucleotide, 'N')  # Handle unexpected characters
    return complement[::-1]

def calculate_tm(sequence):
    # Calculate the reverse complement of the sequence
    reverse_sequence = reverse_comp(sequence)

Count A-T and G-C pairs in the original sequence and reverse complement
    at_count = sequence.count('A') + sequence.count('T')
    gc_count = sequence.count('G') + sequence.count('C')

Estimate Tm using the Wallace rule
    tm = 2 * at_count + 4 * gc_count

    return tm