# -*- coding: utf-8 -*-
"""Primer design code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137QDdFRwDN-Thw7D0pNVDRCNXfVTcSjo
"""

#Primer Design Code:

sequence = 'ATCGGAGGATTAGGGCAGGAGAGGATCGAGAGAGCGTAGCAGGAGGGATAAATAG'

def comp(seq):
  chargaff = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
  comp = ' '
  for char in seq:
    comp = comp + chargaff[char]
  return comp[::-1]

def primers(seq):
  fwd = seq[:10:]
  rev = seq[-10:]

  return fwd, comp(rev)

forward, reverse = primers(sequence)
print (forward, reverse)