# -*- coding: utf-8 -*-
"""Edge-Primer Design for a Given Sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NeZuUjIhDNrh91X_KzfpXmtJ2LcvpTQ
"""

from re import S
def primers(Sequence: str, primer_length: int) -> dict:

    Sequence = Sequence.upper()


    complement_table = str.maketrans("ATGC", "TACG")


    if Primer_Length > len(Sequence):
        return {"error": "Primer length exceeds sequence length"}

\
    forward_primer = Sequence[:Primer_Length]


    reverse_complement_sequence = Sequence[::-1].translate(complement_table)
    reverse_primer = reverse_complement_sequence[:Primer_Length]

    return {
        "forward_primer": forward_primer,
        "reverse_primer": reverse_primer
    }