# -*- coding: utf-8 -*-
"""Edge-Primer Design for a Given Sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NeZuUjIhDNrh91X_KzfpXmtJ2LcvpTQ
"""

def primer(sequence: str, primer_length: int) -> dict:
    sequence = sequence.upper()


    complement_table = str.maketrans("ATGC", "TACG")

    reverse_complement_sequence = sequence[::-1].translate(complement_table)
    primer = reverse_complement_sequence[:primer_length]

    return {
        "primer": primer
    }



primer_result = primer(Sequence, Primer_Length)
print(primer_result)